server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${db.username}
    password: ${db.password}
    
  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행하는 SQL을 콘솔에 출력
        format_sql: true # 실행되는 SQL의 들여쓰기 및 줄 개행 (형식화)
        use_sql_comments: true # 주석도 같이 만들어서 보여줄지 설정하는 것
        # dialect: org.hibernate.dialect.OracleDialect # DB쿼리를 오라클로 인식하도록 하는 설정
        # 어떤 DB의 쿼리를 만들어줄지 인식하도록 알려주는 설정
        # 예전에는 꼭 이 설정을 해야했다!
    hibernate:
      # ddlAuto: create # DDL 자동으로 해주는 기능!
      ddlAuto: create

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

## 로거 설정
#logging:
#  level:
#    org:
#      hibernate: # Hibernate은 데이터베이스와 자바 객체 간의 매핑을 도와주는 도구
#        type: trace
#        # Hibernate이 실행 중인 어플리케이션에서 매우 상세한 로깅을 활성화